### ISSUE TITLE
Broken script

### ISSUE THREAD

**Issue by mysteryx93** [HomeOfVapourSynthEvolution/nnedi3_resample#1]
I have this xClean script that worked fine.
[https://github.com/mysteryx93/xClean...main/xClean.py](https://github.com/mysteryx93/xClean/blob/main/xClean.py)

(plugins are pulled from the AUR in Linux)

Now, if I run it with chroma="nnedi3", I get this error:

```
Failed to evaluate the script:
Python exception: No attribute with the name get_format exists. Did you mistype a plugin namespace?
line 30, in nnedi3_resample
```

If I set chroma="reconstructor", I get this error:

```
Python exception: No attribute with the name nnedi3cl exists. Did you mistype a plugin namespace?
File "/usr/lib/python3.10/site-packages/nnedi3_resample.py", line 440, in nnedi3_dh
```

First error is due to this
https://github.com/vapoursynth/vapoursynth/blob/b1af67c44fc3bc3365b6ba2494207774a69df4d9/ChangeLog#L12

Second error would indicate that the plugin isn't loaded, but it is installed (from AUR) and pulling from this
[https://github.com/HomeOfVapourSynth...Synth-NNEDI3CL](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-NNEDI3CL)

**Comment by mawen1250** [comment]
1. Solved in https://github.com/HomeOfVapourSynthEvolution/nnedi3_resample/pull/2
2. It seems the error is about plugin loading, maybe you should check if you could directly call core.nnedi3cl.NNEDI3CL?

**Comment by mysteryx93** [comment]
core.nnedi3cl.NNEDI3CL doesn't work, it seems to be an issue with the AUR package. It has the pre-compiled .so library instead of compiling it like other packages. I commented on the AUR package.
